create table public.invoices (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id),
  client_name text not null,
  client_email text not null,
  amount_cents integer not null,
  status text not null,
  due_date date not null,
  notes text
);

grant select, insert, update, delete on public.invoices to anon, authenticated;
